// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoviesSystem.Infrastructure.Store;

namespace MoviesSystem.Infrastructure.Store.Migrations
{
    [DbContext(typeof(MoviesDbContext))]
    [Migration("20211017161113_ChangeColumnName")]
    partial class ChangeColumnName
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MoviesSystem.Infrastructure.Store.Models.WatchListItem", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("MovieId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsWatched")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastNotificationDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "MovieId");

                    b.ToTable("Watchlist");
                });
#pragma warning restore 612, 618
        }
    }
}
